import Foundation

/// Helper to load sensitive configuration like API keys from multiple sources without hard-coding.
/// Order of precedence:
/// 1. Environment variable GROQ_API_KEY (useful for Xcode scheme or CI)
/// 2. Hardcoded key (REPLACE THIS AFTER CLONING)
/// 3. Secrets.plist in the app bundle (if generated by build script)
/// 4. Info.plist key GROQ_API_KEY (less secure, optional)
struct Secrets {
    static var apiKey: String? {
        // 1) Environment (useful for Xcode Run scheme, CI)
        if let env = ProcessInfo.processInfo.environment["GROQ_API_KEY"], !env.isEmpty {
            return env
        }
        
        // 2) Hardcoded key - REPLACE THIS WITH YOUR KEY AFTER CLONING
        // DO NOT COMMIT YOUR REAL KEY TO GIT!
        let hardcodedKey = "YOUR_API_KEY_HERE"
        if !hardcodedKey.isEmpty && hardcodedKey != "YOUR_API_KEY_HERE" {
            return hardcodedKey
        }
        
        // 3) Secrets.plist in bundle (create and add to your app target, but keep it gitignored)
        if let url = Bundle.main.url(forResource: "Secrets", withExtension: "plist"),
           let data = try? Data(contentsOf: url),
           let dict = try? PropertyListSerialization.propertyList(from: data, options: [], format: nil) as? [String: Any],
           let key = dict["GROQ_API_KEY"] as? String,
           !key.isEmpty {
            return key
        }
        
        // 4) Info.plist key (for convenience; avoid committing secrets here in public repos)
        if let infoKey = Bundle.main.object(forInfoDictionaryKey: "GROQ_API_KEY") as? String, !infoKey.isEmpty {
            return infoKey
        }
        
        return nil
    }
}
